name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dar permisos de ejecución a Gradle Wrapper
        run: chmod +x gradlew

      - name: Compilar APK (Build)
        run: ./gradlew build

      - name: Generar APK Debug
        run: ./gradlew assembleDebug

      - name: Guardar APK como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
